from __future__ import annotations

from typing import Any, Mapping, Protocol


class HumanDecisionStore(Protocol):
    """Operational persistence for Human Decision request/response lifecycle."""

    def put_request(self, request: Mapping[str, Any]) -> Mapping[str, Any]: ...
    def get_request(self, request_id: str) -> Mapping[str, Any] | None: ...
    def get_status(self, request_id: str) -> str | None: ...
    def list_pending(self, project_ref: str) -> tuple[Mapping[str, Any], ...]: ...
    def record_rejected_response(self, request_id: str, response: Mapping[str, Any], reason: str) -> None: ...
    def claim_response(self, request_id: str, request_digest: str, response: Mapping[str, Any]) -> str: ...
    def finalize(self, request_id: str, response_digest: str, status: str, *, commit_receipt: Mapping[str, Any] | None = None, detail: str | None = None) -> None: ...
